apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-single-env
spec:
  containers:
  - name: secret-container
    image: nginx:1.16
    envFrom:
    - secretRef:
        name: sample-db-auth
      prefix: DB1_
