apiVersion: batch/v1
kind: Job
metadata:
  name: sanmple-job-single
spec:
  ttlSecondsAfterFinished: 30
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: tools-container
        image: amsy810/tools:v2.0
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
